import React from 'react'

export const LOREM_TEXT = {
  text: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer metus nunc, lobortis eget magna et, suscipit dignissim erat. Mauris quis augue ultricies, tincidunt metus sit amet, tristique erat. Quisque venenatis lacus eget justo luctus, eget maximus sapien vulputate. Nam a magna ac arcu fermentum accumsan. Maecenas urna nisl, vulputate at justo sed, euismod cursus lectus. Donec a ultrices nisi, vel imperdiet nisi. Phasellus euismod arcu in blandit mollis. Aenean sit amet accumsan purus. Etiam tempor mollis arcu. Pellentesque molestie, odio varius pellentesque congue, nibh mi iaculis eros, id vestibulum nibh quam in leo. Suspendisse fringilla accumsan ligula et finibus. Proin tincidunt, odio cursus luctus dignissim, massa sapien varius lectus, sed volutpat urna mauris at neque.

    Mauris a tellus auctor, ornare nibh id, semper orci. Morbi semper tristique odio, auctor condimentum dui elementum quis. Cras eget libero nibh. Morbi ac arcu dui. Quisque vitae massa purus. Cras ullamcorper tortor sit amet nulla efficitur consectetur. Proin nulla ligula, malesuada vitae imperdiet ac, volutpat sed ex. Sed condimentum turpis ut tincidunt porttitor. Donec mollis mi sed cursus interdum.

    Cras iaculis, est quis feugiat aliquet, libero sapien aliquam lacus, a blandit dui nunc nec dolor. Phasellus nisl ligula, eleifend et lectus eu, interdum congue felis. Fusce dictum massa id eleifend scelerisque. Fusce sed lobortis justo. Vivamus feugiat mattis consequat. Fusce eu orci at turpis dignissim commodo. Aliquam id ligula vel augue mollis dignissim. Sed ullamcorper consequat neque, quis fermentum justo venenatis mattis. Mauris eget enim mattis ipsum malesuada rutrum in eget libero. Nunc ante tortor, porttitor ac nisl vitae, egestas vestibulum erat. Sed at tristique nunc. In hac habitasse platea dictumst. In dictum convallis odio vitae dapibus. Nullam porta magna eget felis luctus ultrices. Curabitur vel laoreet risus.

    Pellentesque et mattis magna, at vehicula ante. Integer faucibus sodales arcu nec imperdiet. Maecenas eget lorem enim. Fusce suscipit sapien a diam fringilla vehicula. Sed aliquam lectus a felis iaculis mollis. Cras suscipit justo vel sapien molestie, vel cursus nulla auctor. Phasellus fringilla orci ac convallis tristique. Nam lacinia cursus velit sit amet maximus. Donec tincidunt arcu massa, et interdum diam convallis in. Maecenas eget tristique diam. Suspendisse congue suscipit mollis. Nunc bibendum ante sit amet dui posuere, vitae iaculis diam mollis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

    Ut in malesuada urna. Donec neque metus, rhoncus non luctus quis, tempus vitae eros. In hac habitasse platea dictumst. Maecenas eu efficitur lacus, viverra egestas massa. Maecenas semper augue augue, vel sagittis justo consectetur at. In ullamcorper nisl ornare dui dictum, non malesuada lectus tempor. Phasellus nec justo at sem lobortis rhoncus. Nam turpis risus, finibus nec dapibus vel, ornare sed elit. Aliquam non blandit tortor. Cras molestie efficitur mauris in aliquet. Maecenas purus nisi, posuere sed suscipit eget, venenatis nec magna. Nam sed leo sagittis, posuere ante vitae, volutpat magna. Nulla eget accumsan nunc. Quisque egestas velit ante.</p>
}